// $ANTLR : "TreeParser.g" -> "ConfigTreeParser.java"$

	package es.us.isa.FAMA.models.config;    
	import java.util.*;	
	import es.us.isa.FAMA.Exceptions.*;
	import es.us.isa.FAMA.models.FAMAAttributedfeatureModel.*;
	import es.us.isa.FAMA.models.featureModel.*;
	import es.us.isa.FAMA.models.featureModel.extended.*;
	import es.us.isa.util.*;
	import es.us.isa.FAMA.models.domain.*;
	import es.us.isa.FAMA.models.domain.RealDomain;
	import es.us.isa.FAMA.parser.*;
	import es.us.isa.FAMA.models.config.*;
	import es.us.isa.FAMA.stagedConfigManager.*;

public interface ConfigTreeParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int FEATURE_MODEL = 4;
	int FEATURE = 5;
	int FEATURES = 6;
	int CONSTRAINTS = 7;
	int CONSTRAINT = 8;
	int DOMINIO = 9;
	int DEF_VALUE = 10;
	int NULL_VALUE = 11;
	int ATRIBUTOS = 12;
	int ATRIBUTO = 13;
	int RELACION = 14;
	int CARDINALIDAD = 15;
	int RELACIONES = 16;
	int INVARIANTES = 17;
	int INVARIANTE = 18;
	int RANGO = 19;
	int LITERAL = 20;
	int RANGOS = 21;
	int VALORES = 22;
	int ENUM = 23;
	int MENOS_UNARIO = 24;
	int CONFIGURACION = 25;
	int SECCION_CONFIGURACION = 26;
	int PyC = 27;
	int IFF = 28;
	int IMPLIES = 29;
	int OR = 30;
	int AND = 31;
	int NOT = 32;
	int MAYOR = 33;
	int MENOR = 34;
	int MAYOR_IGUAL = 35;
	int MENOR_IGUAL = 36;
	int IGUAL = 37;
	int DISTINTO = 38;
	int MAS = 39;
	int MENOS = 40;
	int MULT = 41;
	int DIV = 42;
	int MOD = 43;
	int POW = 44;
	int ABS = 45;
	int SIN = 46;
	int COS = 47;
	int PARENTESIS_ABRIR = 48;
	int PARENTESIS_CERRAR = 49;
	int MAX = 50;
	int MIN = 51;
	int SUM = 52;
	int COMA = 53;
	int IDENT = 54;
	int LIT_REAL = 55;
	int LIT_ENTERO = 56;
	int LIT_STRING = 57;
	int PUNTO = 58;
	int EXCLUDES = 59;
	int REQUIRES = 60;
}
