// $ANTLR : "TreeParser.g" -> "FaMaTreeParser.java"$

	package es.us.isa.FAMA.parser;    
	import java.util.*;	
	import es.us.isa.FAMA.Exceptions.*;
	import es.us.isa.FAMA.models.FAMAAttributedfeatureModel.*;
	import es.us.isa.FAMA.models.featureModel.*;
	import es.us.isa.FAMA.models.featureModel.extended.*;
	import es.us.isa.util.*;
	import es.us.isa.FAMA.models.domain.*;
	import es.us.isa.FAMA.models.domain.RealDomain;
	import es.us.isa.FAMA.parser.*;

public interface FaMaTreeParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int FEATURE_MODEL = 4;
	int FEATURE = 5;
	int FEATURES = 6;
	int CONSTRAINTS = 7;
	int CONSTRAINT = 8;
	int DOMINIO = 9;
	int DEF_VALUE = 10;
	int NULL_VALUE = 11;
	int ATRIBUTOS = 12;
	int ATRIBUTO = 13;
	int RELACION = 14;
	int CARDINALIDAD = 15;
	int RELACIONES = 16;
	int INVARIANTES = 17;
	int INVARIANTE = 18;
	int RANGO = 19;
	int LITERAL = 20;
	int RANGOS = 21;
	int VALORES = 22;
	int ENUM = 23;
	int MENOS_UNARIO = 24;
	int TRUE_VALUE = 25;
	int FALSE_VALUE = 26;
	int SECCION_RELACIONES = 27;
	int DOSPUNTOS = 28;
	int PyC = 29;
	int IDENT = 30;
	int CORCHETE_ABRIR = 31;
	int CORCHETE_CERRAR = 32;
	int LIT_ENTERO = 33;
	int COMA = 34;
	int LLAVE_ABRIR = 35;
	int LLAVE_CERRAR = 36;
	int SECCION_ATRIBUTOS = 37;
	int PUNTO = 38;
	int INTEGER = 39;
	int REAL = 40;
	int TO = 41;
	int LIT_REAL = 42;
	int LIT_STRING = 43;
	int SECCION_CONSTRAINTS = 44;
	int EXCLUDES = 45;
	int REQUIRES = 46;
	int IFF = 47;
	int IMPLIES = 48;
	int OR = 49;
	int AND = 50;
	int NOT = 51;
	int MAYOR = 52;
	int MENOR = 53;
	int MAYOR_IGUAL = 54;
	int MENOR_IGUAL = 55;
	int IGUAL = 56;
	int DISTINTO = 57;
	int MAS = 58;
	int MENOS = 59;
	int MULT = 60;
	int DIV = 61;
	int MOD = 62;
	int POW = 63;
	int ABS = 64;
	int SIN = 65;
	int COS = 66;
	int PARENTESIS_ABRIR = 67;
	int PARENTESIS_CERRAR = 68;
	int MAX = 69;
	int MIN = 70;
	int SUM = 71;
	int INICIO_TABLA = 72;
	int FIN_TABLA = 73;
}
